### PR TITLE
ext_bmiz(), Docker, adjustcf script, and more

### PR DESCRIPTION
**Pull request by dchud**
A set of changes we've been working on at MITRE. Briefly: new ext_bmiz, recode_sex, and longwide functions, as well as Dockerfile, gcdriver commandline script, initial testing, gentle code reorg, and experimental carried forward adjustment; see NEWS.md for details.

Will follow up via email as well, as some of these changes warrant discussion. Wanted to send the code through here as well so you have it.

### CODE REVIEW

**Comment by grundmeier** [comment]
Hello, I see R/adjustcarryforward.R includes plyr (which I recall was used for our early attempts at supporting parallel processing), but I don't see that it is being used.  Does it need to be imported?

Similarly, I see jsonlite imported in a couple of files, but I'm not sure if it is being used (sorry if I missed it). Also, it doesn't appear to be in the list of dependencies (at least not that I can see, unless something else depends on it).

**Comment by dcam2015** [comment]
@grundmeier `plyr` is being used in the following line `growth.R` file with the `ddply` function https://github.com/carriedaymont/growthcleanr/blob/master/R/growth.R#L1272, but perhaps there can be a `dplyr` version that can be utilized there instead in a future update.

I agree about `jsonlite` perhaps not being needed; I don't see the usual `fromJson()` function that is usually used from that library.

**Comment by dchud** [comment]
@grundmeier @dcam2015 jsonlite imports were a mistake, and are removed as of 9bc5c40. Thanks for catching!

**Comment by grundmeier** [comment]
Thanks! Everything looks good!

**Pull request merged**
