### PR TITLE
Update CRAN initial submission #3

### LINKED ISSUE #83: Fixing CRAN pretest attempt 2
Need to fix cleangrowth example time length (see attached).

[00details.log](https://github.com/carriedaymont/growthcleanr/files/9365088/00details.log)

### PR DESCRIPTION
**Pull request by delosh653**
Moves cleangrowth example to `donttest` and adds CRAN comments file. Fixes #83 (Fixing CRAN pretest attempt 2).

### CODE REVIEW

**Review by dchud — CHANGES_REQUESTED** [review]
Should `cran-comments.md` maybe just stay attached to #82/#83 instead of including it in the package? It looks like having this file commited to the actual repo kicks up a new note from `devtools::check()`.

Unless this is part of the process, that they want to see the specific comments in a file in the repo with this name... :)

**Comment by dchud** [comment]
(...reads more...) ah, so perhaps you're using https://usethis.r-lib.org/reference/use_cran_comments.html? What I don't see is how this file then gets cleaned up from the repo, or if it stays in for future submissions, etc.

**Comment by delosh653** [comment]
> Should `cran-comments.md` maybe just stay attached to #82/#83 instead of including it in the package? It looks like having this file commited to the actual repo kicks up a new note from `devtools::check()`.
> 
> Unless this is part of the process, that they want to see the specific comments in a file in the repo with this name... :)

Whoops, forgot to add it to .Rbuildignore! (added) But the idea of having the markdown be persistent is to have a record of submissions (to also make it easy for future submissions: https://r-pkgs.org/release.html). But I could see wanting to remove the previous submission comments and just have them in git history. Let me know what you want to do on that.

**Review by dchud — APPROVED** [review]
Looks good!

**Pull request merged**
