### PR TITLE
Moved README.md to README.Rmd, closes #17

### LINKED ISSUE #17: Switch README to use Rmd
Following @mcanouil's suggestion at https://github.com/carriedaymont/growthcleanr/pull/9, switch README to be generated from Rmd.

### PR DESCRIPTION
**Pull request by dchud**
This is a few steps toward the full-evaluation approach from @mcanouil in #9, but holds back from evaluating most of the code examples for short-term, practical reasons:

- The main README is way too long; we intend to break it up into smaller vignettes (added #30)
- If all the code is evaluated, it takes too long in its current over-lengthy state

It should be easy to add evaluation back once we break it up a bit.

### CODE REVIEW

**Comment by dchud** [comment]
I suspect that failed build at https://github.com/carriedaymont/growthcleanr/pull/31/checks?check_run_id=1785992844 was a build-side problem, looks like a missing package.

**Review by delosh653 — COMMENTED** [review]
Looks good, though, in the future, it might be nice to have a small tailored dataset we could run through to make those chunks actually run.

**Review by delosh653 — APPROVED** [review]

**Comment by dchud** [comment]
@delosh653 I agree re: smaller dataset. Perhaps we pull a subset deterministically out of `syngrowth` for the new vignettes.

**Comment by dchud** [comment]
Re-test clears up the build server issue without further changes, merging.

**Pull request merged**
