### PR TITLE
Remove dependencies, warnings and optimise code (Major changes)

### PR DESCRIPTION
**Pull request by mcanouil**
Hi,

I am going to use this package a lot and at first, I used the scripts from the article.
I have forked and make (a lot of) changes described below.

``` 
==> devtools::test()

Loading growthcleanr
Testing growthcleanr
✓ |  OK F W S | Context
✓ |   5       | cdc [0.8 s]
✓ |   8       | cleangrowth [16.5 s]
✓ |  76       | utils [28.9 s]

══ Results ════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 46.2 s

OK:       89
Failed:   0
Warnings: 0
Skipped:  0
```

Best regards,

* * *

### Changelog: 
* Includes the proposed changes from https://github.com/carriedaymont/growthcleanr/pull/6
* Includes the proposed changes from https://github.com/carriedaymont/growthcleanr/pull/7
* Includes the proposed changes from https://github.com/mitre/growthcleanr/pull/7
* Uses actual boolean variable instead of shortcuts to avoid the behaviour below:
    ``` r
    T <- 25
    T
    #> [1] 25
    TRUE <- 25
    #> Error in TRUE <- 25: invalid (do_set) left-hand side to assignment
    ```
* Uses `setkeyv` instead of `setkey` to reduce the global variables checks warnings (if the package is at some point intended to be deployed on CRAN)
* Refactoring to make the code more readable and consistent across the package (except `tests/`)
* Split big R files into several ones per functions, to ease the update and changes, which with several thousands lines is hard.
* Remove dependency to `Hmisc`, `dplyr` and `tidyr`, which was not needed since the main framework is `data.table`.
* Add `stats` in `Imports`.
* Add `R (>= 3.6.0)` in `Depends`.
* Complete rewrite of `read_anthro()` and `long_wide()`.
* In `Dockerfile`, now dependencies are installed from `growthcleanr` in one command.
* Fix examples errors related to code changes.
* Fix `"no visible binding for global variable"` from `data.table`. (https://rdatatable.gitlab.io/data.table/articles/datatable-importing.html)
* Use github action to run `devtools::check()` instead of using travis as proposed in https://github.com/carriedaymont/growthcleanr/pull/8.

### To do (maybe):
* `README-adjustcarryforward.md` as a vignette.
    ``` r
    > checking top-level files ... NOTE
      Non-standard file/directory found at top level:
        ‘README-adjustcarryforward.md’
    ```
* Fix documentation issues
    ``` r
    W  checking Rd \usage sections ...
       Undocumented arguments in documentation object 'cleangrowth'
         ‘height.tolerance.cm’
       
       Undocumented arguments in documentation object 'long_wide'
         ‘clean_value’
    ```
* Reduce complexity of `cleanbatch()`, `cleangrowth()` and `adjustcarryforward()`, *e.g.*, by externalising the shared code into a function.
* Replace the following code (same approach in different places) using `findInterval()`.
    ``` r
    # 15h.	Generate variable whoinc_age_ht based on values of d_agedays_ht according the the following table
    #   d_agedays_ht	whoinc_age_ht
    #   20-45	        1
    #   46-75	        2
    #   76-106	      3
    #   107-152	      4
    #   153-198	      6
    #   All others	  missing
    df[, whoinc.age.ht := ifelse(delta.agedays.next < 20,
      NA,
      ifelse(
        delta.agedays.next <= 45,
        1,
        ifelse(
          delta.agedays.next <= 75,
          2,
          ifelse(
            delta.agedays.next <= 106,
            3,
            ifelse(
              delta.agedays.next <= 152,
              4,
              ifelse(delta.agedays.next <= 198, 6, NA)
            )
          )
        )
      )
    )]
    ```
* Update documentation to use reference across functions to avoid repeating information and miss one when there is an update.

* * *

``` 
==> devtools::check(build_args = c('--resave-data'))

Updating growthcleanr documentation
Loading growthcleanr
Writing NAMESPACE
Writing NAMESPACE
── Building ─────────────────────────────────────────────────────────────────────────────────── growthcleanr ──
Setting env vars:
● CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
● CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
● CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
✓  checking for file ‘/disks/PROJECT/_Mickael/PACKAGES/growthcleanr/DESCRIPTION’ (339ms)
─  preparing ‘growthcleanr’: (2.7s)
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts (927ms)
─  checking for empty or unneeded directories
─  building ‘growthcleanr_1.2.2.tar.gz’
   
── Checking ─────────────────────────────────────────────────────────────────────────────────── growthcleanr ──
Setting env vars:
● _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
● _R_CHECK_CRAN_INCOMING_       : FALSE
● _R_CHECK_FORCE_SUGGESTS_      : FALSE
● NOT_CRAN                      : true
── R CMD check ─────────────────────────────────────────────────────────────────
─  using log directory ‘/disks/PROJECT/_Mickael/PACKAGES/growthcleanr.Rcheck’ (364ms)
─  using R version 4.0.3 (2020-10-10)
─  using platform: x86_64-pc-linux-gnu (64-bit)
─  using session charset: UTF-8
─  using options ‘--no-manual --as-cran’ (717ms)
✓  checking for file ‘growthcleanr/DESCRIPTION’
─  checking extension type ... Package
─  this is package ‘growthcleanr’ version ‘1.2.2’
─  package encoding: UTF-8
✓  checking package namespace information
N  checking package dependencies (3s)
   Package suggested but not available for checking: ‘argparse’
✓  checking if this is a source package ...
✓  checking if there is a namespace
✓  checking for executable files (490ms)
✓  checking for hidden files and directories ...
✓  checking for portable file names ...
✓  checking for sufficient/correct file permissions
✓  checking whether package ‘growthcleanr’ can be installed (7.1s)
N  checking installed package size ...
     installed size is  8.3Mb
     sub-directories of 1Mb or more:
       extdata   7.7Mb
✓  checking package directory (661ms)
✓  checking for future file timestamps (3.2s)
✓  checking DESCRIPTION meta-information (495ms)
N  checking top-level files
   Non-standard file/directory found at top level:
     ‘README-adjustcarryforward.md’
✓  checking for left-over files ...
✓  checking index information ...
✓  checking package subdirectories ...
✓  checking R files for non-ASCII characters ...
✓  checking R files for syntax errors ...
✓  checking whether the package can be loaded (839ms)
✓  checking whether the package can be loaded with stated dependencies (686ms)
✓  checking whether the package can be unloaded cleanly (729ms)
✓  checking whether the namespace can be loaded with stated dependencies (702ms)
✓  checking whether the namespace can be unloaded cleanly (774ms)
✓  checking loading without being on the library search path (1s)
✓  checking dependencies in R code (946ms)
✓  checking S3 generic/method consistency (1.4s)
✓  checking replacement functions (727ms)
✓  checking foreign function calls (844ms)
✓  checking R code for possible problems (7.9s)
✓  checking Rd files (483ms)
✓  checking Rd metadata ...
✓  checking Rd line widths ...
✓  checking Rd cross-references ...
✓  checking for missing documentation entries (805ms)
✓  checking for code/documentation mismatches (2.1s)
W  checking Rd \usage sections ...
   Undocumented arguments in documentation object 'cleangrowth'
     ‘height.tolerance.cm’
   
   Undocumented arguments in documentation object 'long_wide'
     ‘clean_value’
   
   Functions with \usage entries need to have the appropriate \alias
   entries, and all their arguments documented.
   The \usage entries must correspond to syntactically valid R code.
   See chapter ‘Writing R documentation files’ in the ‘Writing R
   Extensions’ manual.
✓  checking Rd contents (1.5s)
✓  checking for unstated dependencies in examples ...
✓  checking contents of ‘data’ directory ...
✓  checking data for non-ASCII characters (408ms)
✓  checking data for ASCII and uncompressed saves (369ms)
✓  checking examples (17.1s)
   Examples with CPU (user + system) or elapsed time > 5s
                       user system elapsed
   split_input        7.836  0.004   7.885
   adjustcarryforward 6.196  0.160   1.795
   cleangrowth        5.708  0.208   2.153
   long_wide          5.460  0.004   1.245
✓  checking for unstated dependencies in ‘tests’ ...
─  checking tests ...
✓  Running ‘testthat.R’ [61s/43s] (43s)
✓  checking for non-standard things in the check directory (43s)
✓  checking for detritus in the temp directory
   
   See
     ‘/disks/PROJECT/_Mickael/PACKAGES/growthcleanr.Rcheck/00check.log’
   for details.
   
   
── R CMD check results ───────────────────────────────── growthcleanr 1.2.2 ────
Duration: 1m 41.8s

> checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'cleangrowth'
    ‘height.tolerance.cm’
  
  Undocumented arguments in documentation object 'long_wide'
    ‘clean_value’
  
  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

> checking package dependencies ... NOTE
  Package suggested but not available for checking: ‘argparse’

> checking installed package size ... NOTE
    installed size is  8.3Mb
    sub-directories of 1Mb or more:
      extdata   7.7Mb

> checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    ‘README-adjustcarryforward.md’

0 errors ✓ | 1 warning x | 3 notes x
```

### CODE REVIEW

**Comment by dchud** [comment]
@mcanouil sorry for the delay, and thanks again for the big contribution!

It might help to share a little more detail about how we've been working on this. @delosh653 and I are working on this through our organization in support of a contract with the US CDC, and in close coordination with @carriedaymont and @grundmeier as part of that work. Our current objectives include improving the algorithm to adapt the height velocity method for re-evaluating carried forward height values, and expanding the package to support cleaning of adult height and weight data. The latter work on adult data is in process and we have a separate testing tool we may be able to share down the road. Through it all we are taking advantage of opportunities to make the package stronger, more flexible, and easier to use for researchers.

With all that in mind, your ideas for enhancements align well with our objectives and we would like to work with you to incorporate them - but probably not all at once, via this PR, for a few reasons. Most practically, it's big! It covers a lot of ground, and works around those pending PRs, and we would like to review and integrate different components of it separately to be thorough. Secondarily, we are planning to work with @grundmeier next week to review those pending PRs and move ahead as appropriate, so that alone will shrink the footprint some.

If you're up for it, we'd like to break this into smaller PRs and address those in turn with a more of a thematic focus. For example, and as a show of good faith, the GitHub Actions workflow here is great, and a simplification over the third-party dependency of using TravisCI, so I've pulled that into a separate PR (https://github.com/carriedaymont/growthcleanr/pull/11) with minor tweaks to get the ball rolling.

Other change categories, each of which could be one or more separate PRs:
* Packaging - we want to proceed with several of your suggestions, such as improvements to package metadata files, using RMarkdown for the README, and cleaning up `CHECK` output
* Code organization - agree that we should split up some of the longest files, but perhaps with more of a thematic focus for some of the utilities (perhaps based on external/internal) together in fewer files rather than having some very brief functions in their own files
* Code style - agree here on using `TRUE`/`FALSE`, `"` more consistently, `stats` package

A few other things, like the `Dockerfile` improvements, could be very simple PRs, too.

If that seems reasonable, and you don't mind another brief delay, we'll work through those other pending PRs next week and follow up with some more concrete suggestions via PRs.

Thanks again for your interest and we look forward to collaborating with you on this!

**Comment by mcanouil** [comment]
Hi @dchud 

thanks for the clarification about your review process.
Here is my proposal to split my PR according to your guidelines:
1. Either:
    * wait for #6 and #7 to be validated
    * PR with #6 and #7 merged (since both PR involve the same files resulting in a small conflict) which could be validated afterwards instead of #6 and #7 (https://github.com/carriedaymont/growthcleanr/pull/9/commits/2f8fcecbf34c3632173210f69234d51a01ab7b20)
2. One major PR (roughly 95 % of all changes in the current PR), which is the code refactoring and the dependencies removal. (without changes to Dockerfile, github actions, documentation files, etc.)
3. PR for Dockerfile improvements
4. PR for Rmarkdown `README`

If this suits you (and your colleagues), I can split my PR accordingly.

Maybe worth to open an issue with a check list about code changes/improvements as below?
* [ ] `README-adjustcarryforward.md` as a vignette.
    ``` r
    > checking top-level files ... NOTE
      Non-standard file/directory found at top level:
        ‘README-adjustcarryforward.md’
    ```
* [ ] Fix documentation issues
    ``` r
    W  checking Rd \usage sections ...
       Undocumented arguments in documentation object 'cleangrowth'
         ‘height.tolerance.cm’
       
       Undocumented arguments in documentation object 'long_wide'
         ‘clean_value’
    ```
* [ ] Reduce complexity of `cleanbatch()`, `cleangrowth()` and `adjustcarryforward()`, *e.g.*, by externalising the shared code into a function.
* [ ] Replace the following code (same approach in different places) using `findInterval()`.
    ``` r
    # 15h.	Generate variable whoinc_age_ht based on values of d_agedays_ht according the the following table
    #   d_agedays_ht	whoinc_age_ht
    #   20-45	        1
    #   46-75	        2
    #   76-106	      3
    #   107-152	      4
    #   153-198	      6
    #   All others	  missing
    df[, whoinc.age.ht := ifelse(delta.agedays.next < 20,
      NA,
      ifelse(
        delta.agedays.next <= 45,
        1,
        ifelse(
          delta.agedays.next <= 75,
          2,
          ifelse(
            delta.agedays.next <= 106,
            3,
            ifelse(
              delta.agedays.next <= 152,
              4,
              ifelse(delta.agedays.next <= 198, 6, NA)
            )
          )
        )
      )
    )]
    ```
* [ ] Update documentation to use reference across functions to avoid repeating information and miss one when there is an update.

**Comment by dchud** [comment]
@mcanouil thanks again for your patience. As you might have noticed, we were able to integrate #6 and #7 last week, so that resolves that question. We've also integrated testing via your GitHub Actions approach via #11 and #13. This is much better, thanks!

As we're also working away at some other changes, so if it's okay with you, let's knock out some more of the smaller changes first. Following your suggestion above, some new tickets:

* https://github.com/carriedaymont/growthcleanr/issues/17 - switch README to use Rmd
* https://github.com/carriedaymont/growthcleanr/issues/18 - fix documentation issues
* https://github.com/mitre/growthcleanr/issues/2 - Dockerfile improvements; I'll post a PR for this.
* https://github.com/carriedaymont/growthcleanr/issues/19 - use `findInterval()`
* Packaging improvements (ticket to come)

A few more notes:

* We'll want to discuss a bit on reorganizing and refactoring functions, so finishing these others first should make that process a little easier.
* We're actively iterating on the `adjustcarryforward` strategy, and still plan to integrate its logic back into the main algorithm in `cleangrowth()`, so for now let's hold off on refactoring it.
* Please feel free to add minor changes to files like `.gitignore` with other PRs whenever appropriate.

I will try to prep PRs myself in the next few days for some of the new tickets so we can split the work a bit so it won't all be on you! I'll assign a ticket myself before starting work on each so it's clear.

**Comment by dchud** [comment]
Hi @mcanouil - I'm sorry it's been so long, but we needed to push on the adult algorithm side to get https://github.com/carriedaymont/growthcleanr/releases/tag/v2.0.0 out the door before our current work program wraps up. I think we've addressed a good number of issues you've raised:

- improved docs (using vignettes, pkgdown, .Rmd files)
- build (`CHECK` output) is clean
- updated `Dockerfile`
- added GitHub actions for testing

We're still hoping to iterate on `adjustcarryforward` but perhaps not for another few months - that is in process.

I will follow up and resolve #19, where it seemed like the changes we came up with were a bit 50/50.

We're still open to your other suggestions for refactoring the code but just didn't end up having time to work through them.

For reference, we noted a few things we'd still like to do (including `adjustcarryforward`) in the [next steps vignette](https://carriedaymont.github.io/growthcleanr/articles/next-steps.html).

At this point, is it fair if we close this for now, and ask that any further changes you'd suggest come in through new tickets/PRs?

**Comment by mcanouil** [comment]
Hi, 
no worries!
I'm closing this PR and propose smaller PRs next time ^^

**Pull request closed without merging**
